// The encrypted asset payload built into NoveskeChainsaw.dll. Shared by the plugin (reader) and
// tools/pack (writer), so both sides use the same format and crypto.
//
// The 3DMA art must not be extractable from the DLL, so no asset is stored as a file: there are no
// PNG/OBJ signatures, names or plain bytes in the binary. Layout (little-endian):
//
//   Header   magic "NVK1", entry count
//   Entry    [count]   salted name hash, flags, sizes, offset, GCM nonce + tag
//   data     each entry's bytes: the file (LZMS-compressed when that helped), AES-256-GCM
//            encrypted with the build's key, the name hash as associated data
//
// The key is random per build and compiled into the plugin (payload_key.h, generated by pack).
// GCM authenticates every entry, so a modified payload is refused rather than decoded.
#pragma once
#include <windows.h>
#include <bcrypt.h>
#include <compressapi.h>
#include <cstdint>
#include <cstring>
#include <string_view>
#include <vector>
#pragma comment(lib, "bcrypt.lib")
#pragma comment(lib, "cabinet.lib")

namespace payload {

constexpr char kMagic[4] = {'N', 'V', 'K', '1'};
constexpr uint32_t kCompressed = 1;

#pragma pack(push, 1)
struct Header {
    char magic[4];
    uint32_t count;
};
struct Entry {
    uint64_t nameHash;
    uint32_t flags;
    uint32_t rawSize;     // bytes after decompression
    uint32_t storedSize;  // bytes of ciphertext
    uint32_t offset;      // from the start of the payload
    uint8_t nonce[12];
    uint8_t tag[16];
};
#pragma pack(pop)

// Salted FNV-1a: entries are looked up by hash, so no asset names are stored.
inline uint64_t Hash(std::string_view name) {
    uint64_t h = 0xcbf29ce484222325ull;
    for (char c : std::string_view("nvk1:")) h = (h ^ (uint8_t)c) * 0x100000001b3ull;
    for (char c : name) h = (h ^ (uint8_t)c) * 0x100000001b3ull;
    return h;
}

inline void Wipe(std::vector<uint8_t>& v) {
    if (!v.empty()) SecureZeroMemory(v.data(), v.size());
    v.clear();
    v.shrink_to_fit();
}

// AES-256-GCM over `size` bytes. Encrypting writes `tag`; decrypting verifies it and fails on any
// modification of the data, the tag, the nonce or the associated data.
inline bool Gcm(bool encrypt, const uint8_t key[32], const uint8_t nonce[12], uint8_t tag[16], uint64_t aad,
                const uint8_t* in, uint8_t* out, uint32_t size) {
    BCRYPT_ALG_HANDLE alg = nullptr;
    BCRYPT_KEY_HANDLE k = nullptr;
    bool ok = false;
    if (BCryptOpenAlgorithmProvider(&alg, BCRYPT_AES_ALGORITHM, nullptr, 0) == 0 &&
        BCryptSetProperty(alg, BCRYPT_CHAINING_MODE, (PUCHAR)BCRYPT_CHAIN_MODE_GCM, sizeof(BCRYPT_CHAIN_MODE_GCM), 0) == 0 &&
        BCryptGenerateSymmetricKey(alg, &k, nullptr, 0, (PUCHAR)key, 32, 0) == 0) {
        BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO info;
        BCRYPT_INIT_AUTH_MODE_INFO(info);
        info.pbNonce = (PUCHAR)nonce;
        info.cbNonce = 12;
        info.pbTag = tag;
        info.cbTag = 16;
        info.pbAuthData = (PUCHAR)&aad;
        info.cbAuthData = sizeof aad;
        ULONG n = 0;
        NTSTATUS s = encrypt ? BCryptEncrypt(k, (PUCHAR)in, size, &info, nullptr, 0, out, size, &n, 0)
                             : BCryptDecrypt(k, (PUCHAR)in, size, &info, nullptr, 0, out, size, &n, 0);
        ok = s == 0 && n == size;
    }
    if (k) BCryptDestroyKey(k);
    if (alg) BCryptCloseAlgorithmProvider(alg, 0);
    return ok;
}

// Decrypts (and decompresses) asset `name` into `out`. False if it is missing, the payload was
// modified, or it doesn't decode. Callers Wipe() `out` once the engine has taken the data.
inline bool Extract(const void* blob, size_t blobSize, const uint8_t key[32], std::string_view name,
                    std::vector<uint8_t>& out) {
    auto* h = (const Header*)blob;
    if (!blob || blobSize < sizeof(Header) || memcmp(h->magic, kMagic, 4) != 0) return false;
    if (sizeof(Header) + (size_t)h->count * sizeof(Entry) > blobSize) return false;
    auto* e = (const Entry*)(h + 1);
    const uint64_t want = Hash(name);
    for (uint32_t i = 0; i < h->count; i++) {
        if (e[i].nameHash != want) continue;
        if ((size_t)e[i].offset + e[i].storedSize > blobSize || e[i].storedSize == 0) return false;
        std::vector<uint8_t> plain(e[i].storedSize);
        uint8_t tag[16];
        memcpy(tag, e[i].tag, sizeof tag);
        if (!Gcm(false, key, e[i].nonce, tag, e[i].nameHash, (const uint8_t*)blob + e[i].offset, plain.data(),
                 e[i].storedSize)) {
            Wipe(plain);
            return false;
        }
        if (!(e[i].flags & kCompressed)) {
            Wipe(out);
            out.swap(plain);
            return true;
        }
        DECOMPRESSOR_HANDLE d = nullptr;
        Wipe(out);
        out.resize(e[i].rawSize);
        SIZE_T n = 0;
        bool ok = CreateDecompressor(COMPRESS_ALGORITHM_LZMS, nullptr, &d) &&
                  Decompress(d, plain.data(), plain.size(), out.data(), out.size(), &n) && n == e[i].rawSize;
        if (d) CloseDecompressor(d);
        Wipe(plain);
        if (!ok) Wipe(out);
        return ok;
    }
    return false;
}

}  // namespace payload
